[package]
name = "lock_and_burn"
version = "0.0.1"
authors = []

[addresses]
my_addr='0x123'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
